# agents/ops_commander.py
#
# This is the one that makes the "mesh" idea actually pay off. Instead of
# reading raw telemetry itself, it takes what Crowd Marshal and GreenRoute
# already generated and fuses them into one situation report — basically
# how a duty manager reads reports from field teams rather than staring at
# raw sensor feeds directly.

from __future__ import annotations

from .base_agent import BaseAgent
from .crowd_marshal import CrowdMarshalAgent
from .green_route import GreenRouteAgent


class OpsCommanderAgent(BaseAgent):
    name = "Ops Commander"
    audience = "Venue Control Room"

    def situation_report(self) -> dict:
        snapshot = self.graph.snapshot()

        crowd_result = CrowdMarshalAgent(self.graph, self.client).briefing()
        green_result = GreenRouteAgent(self.graph, self.client).recommend(party_size=200, distance_km=6.0)
        incidents = snapshot["recent_incidents"]

        system_prompt = (
            "You are Ops Commander, the control-room fusion assistant for a FIFA World Cup "
            "2026 stadium. You receive outputs already generated by two specialist agents "
            "(crowd management and sustainability/transport) plus a live incident log. Fuse "
            "them into a single, professional situation report for the duty manager: a short "
            "headline, then 3-5 bullet-style lines (use '- ' prefix), covering crowd status, "
            "transport status, and any incidents. End with one clear recommended priority "
            "action. Keep it tight and operational — this is read on a live shift, not a report."
        )

        user_prompt = (
            f"Crowd Marshal briefing: {crowd_result['text']}\n\n"
            f"GreenRoute recommendation: {green_result['text']}\n\n"
            f"Recent incidents (most recent last): {incidents}\n\n"
            f"Weather: {snapshot['weather']}\n\n"
            "Produce the fused situation report."
        )

        def fallback() -> str:
            lines = ["SITUATION REPORT — Live Stadium Status"]
            lines.append(f"- Crowd: {crowd_result['text']}")
            lines.append(f"- Transport/Sustainability: {green_result['text']}")
            if incidents:
                latest = incidents[-1]["message"]
                lines.append(f"- Latest incident log entry: {latest}")
            else:
                lines.append("- No active incidents logged.")
            lines.append(f"- Weather: {snapshot['weather']['condition']}, {snapshot['weather']['temp_c']}°C")
            priority = (
                "Priority action: address gate surge first."
                if crowd_result.get("surge_detected")
                else "Priority action: none critical — continue routine monitoring."
            )
            lines.append(f"- {priority}")
            return "\n".join(lines)

        result = self._run(system_prompt, user_prompt, fallback, max_tokens=400)
        result["surge_detected"] = crowd_result.get("surge_detected", False)
        result["sub_agent_outputs"] = {
            "crowd_marshal": crowd_result,
            "green_route": green_result,
        }
        return result
